name: CI golang workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    name: check-application
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go: [1.22, 1.23]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up golang
        uses: actions/setup-go@v6
        with:
          go-version: 1.22
      - name: Executando testes e rodando a aplicacao
        run: |
          go test
          go run math.go
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: docker_builder
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: italooliveirash/integracao-continua-go:latest